name: Deploy android to firebase
on:
  push:
    branches:
      - firebase
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Build android apk
        run: |
          cd android
          ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: android/app/build/outputs/apk/release/app-release.apk
          groups: internal